version: v2
name: Swift Lint
slug: swift-lint
type: content
summary: A tool to enforce Swift style and conventions.
description: |
  A tool to enforce Swift style and conventions.
subscription_level: 1
default_configuration:
  installation:
    org: false
memory: 512
timeout: 240
storage: 1024
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested