version: v2
name: Swift Lint
slug: swift-lint
type: code_analysis
summary: Update me
description: |
  Fill me out
subscription_level: 1
default_configuration:
  installation:
    org: false
parameters:
  - name: foo
    description: bar

subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested